name: entity-manager-dev

services:
  backend:
    build:
      context: server
      target: dev
      dockerfile: Dockerfile
    image: em-backend
    restart: unless-stopped
    ports:
      - "8090:3000"
    environment:
      APP_NAME: Entity-Manager-Backend
    env_file:
      - path: server/.env
        required: true
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./server/package.json
          target: /app/package.json


  frontend:
    build:
      context: client
      target: dev
      dockerfile: Dockerfile
    image: em-frontend
    restart: unless-stopped
    ports:
      - "8080:4200"
    environment:
      APP_NAME: Entity-Manager
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./client/package.json
          target: /app/package.json
